#!/bin/sh -ex

cc \
	-O3 \
	-fsanitize=undefined,address \
	-std=c11 -Wextra -Werror -pedantic \
	-fPIC \
	-shared \
	-fvisibility=hidden \
	-Wl,--exclude-libs,ALL \
	-Wl,--no-whole-archive \
	-o plugin.so \
	example_plugin.c

cc \
	-O3 \
	-std=c11 -Wextra -Werror -pedantic \
	-fsanitize=undefined,address \
	-o host \
	example_host.c
